config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :masterkeys
  resources :message_histories
  resources :messages
  # resources :students

  resources :students do
    collection do
      get 'deleteAll'
    end
  end

  resources :students_imports, only: %i[new create]

  get 'students_imports/new'
  get 'students_imports/create'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'user' }

  resources :message_histories
  resources :carriers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posttext', to: 'posttext#posttext'
  get 'home/dashboard'
  get 'home/homepage'
  root 'posttext#posttext'

  get  'help', to: 'help#index'
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  validates :admin_id, presence: true
  validates :text, presence: true
  validates :date_created, presence: true
  has_many :student
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# comment
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show; end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit; end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:admin_id, :text, :date_created)
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to '<button type="button">Edit</button>'.html_safe, @message %> |
<%= link_to '<button type="button">Back</button>'.html_safe, messages_path %>

<script>
	// highlight the current page
	var element = document.getElementById("4");
	element.classList.add("active");
</script>

app/views/messages/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Students</title>
</head>
<body id="body-pd">

  <h1>Admin Messages</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Admin</th>
        <th>Text</th>
        <th>Date created</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= message.admin_id %></td>
          <td><%= message.text %></td>
          <td><%= message.date_created %></td>
          <td><%= link_to '<i class="bx bx-search nav_icon"></i>'.html_safe, message %></td>
          <td><%= link_to '<i class="bx bx-pencil nav_icon"></i>'.html_safe, edit_message_path(message) %></td>
          <td><%= link_to '<i class="bx bx-trash nav_icon"></i>'.html_safe, message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br> 

</body>
</html>

<script>
	// highlight the current page
	var element = document.getElementById("4");
	element.classList.add("active");
</script>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>


<%= link_to '<button type="button">Back</button>'.html_safe, messages_path %>

<script>
	// highlight the current page
	var element = document.getElementById("4");
	element.classList.add("active");
</script>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @message.admin_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @message.date_created %>
</p>


<%= link_to '<button type="button">Edit</button>'.html_safe, edit_message_path(@message) %> |
<%= link_to '<button type="button">Back</button>'.html_safe, messages_path %>

<script>
	// highlight the current page
	var element = document.getElementById("4");
	element.classList.add("active");
</script>