config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :masterkeys
  resources :message_histories
  resources :messages
  # resources :students

  resources :students do
    collection do
      get 'deleteAll'
    end
  end

  resources :students_imports, only: %i[new create]

  get 'students_imports/new'
  get 'students_imports/create'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'user' }

  resources :message_histories
  resources :carriers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posttext', to: 'posttext#posttext'
  get 'home/dashboard'
  get 'home/homepage'
  root 'posttext#posttext'

  get  'help', to: 'help#index'
end

app/models/masterkey.rb
# frozen_string_literal: true

class Masterkey < ApplicationRecord
  validates :key, presence: true
end

app/controllers/masterkeys_controller.rb
# frozen_string_literal: true

# comment
class MasterkeysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_masterkey, only: %i[show edit update destroy]

  # GET /masterkeys or /masterkeys.json
  def index
    @masterkeys = Masterkey.all
  end

  # GET /masterkeys/1 or /masterkeys/1.json
  def show; end

  # GET /masterkeys/new
  def new
    @masterkey = Masterkey.new
  end

  # GET /masterkeys/1/edit
  def edit; end

  # POST /masterkeys or /masterkeys.json
  def create
    @masterkey = Masterkey.new(masterkey_params)

    respond_to do |format|
      if @masterkey.save
        format.html { redirect_to masterkey_url(@masterkey), notice: 'Masterkey was successfully created.' }
        format.json { render :show, status: :created, location: @masterkey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @masterkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masterkeys/1 or /masterkeys/1.json
  def update
    respond_to do |format|
      if @masterkey.update(masterkey_params)
        format.html { redirect_to masterkey_url(@masterkey), notice: 'Masterkey was successfully updated.' }
        format.json { render :show, status: :ok, location: @masterkey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @masterkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masterkeys/1 or /masterkeys/1.json
  def destroy
    @masterkey.destroy

    respond_to do |format|
      format.html { redirect_to masterkeys_url, notice: 'Masterkey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_masterkey
    @masterkey = Masterkey.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def masterkey_params
    params.require(:masterkey).permit(:key)
  end
end

app/helpers/masterkeys_helper.rb
# frozen_string_literal: true

module MasterkeysHelper
end

app/views/masterkeys/_form.html.erb
<%= form_with(model: masterkey) do |form| %>
  <% if masterkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(masterkey.errors.count, "error") %> prohibited this masterkey from being saved:</h2>

      <ul>
        <% masterkey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/masterkeys/edit.html.erb
<h1>Editing Masterkey</h1>

<%= render 'form', masterkey: @masterkey %>

<%= link_to '<button type="button">Edit</button>'.html_safe, @masterkey %> |
<%= link_to '<button type="button">Back</button>'.html_safe, masterkeys_path %>

<script>
	// highlight the current page
	var element = document.getElementById("5");
	element.classList.add("active");
</script>

app/views/masterkeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Masterkeys</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masterkeys.each do |masterkey| %>
      <tr>
        <td><%= masterkey.key %></td>
        <td><%= link_to '<i class="bx bx-pencil nav_icon"></i>'.html_safe, edit_masterkey_path(masterkey) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
	// highlight the current page
	var element = document.getElementById("5");
	element.classList.add("active");
</script>

app/views/masterkeys/new.html.erb
<h1>New Masterkey</h1>

<%= render 'form', masterkey: @masterkey %>

<%= link_to 'Back', masterkeys_path %>

app/views/masterkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @masterkey.key %>
</p>

<%= link_to 'Edit', edit_masterkey_path(@masterkey) %> |
<%= link_to 'Back', masterkeys_path %>