config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :masterkeys
  resources :message_histories
  resources :messages
  # resources :students

  resources :students do
    collection do
      get 'deleteAll'
    end
  end

  resources :students_imports, only: %i[new create]

  get 'students_imports/new'
  get 'students_imports/create'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'user' }

  resources :message_histories
  resources :carriers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posttext', to: 'posttext#posttext'
  get 'home/dashboard'
  get 'home/homepage'
  root 'posttext#posttext'

  get  'help', to: 'help#index'
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  validates :Phone_Number, presence: true
  # :uniqueness => true

  def Phone_Number=(value)
    value = stripDigits(stripNonIntegers(value.to_s)).to_i
    super(value)
  end

  def stripWhitespace(str)
    str.gsub(/\s+/, '')
  end

  def stripNonIntegers(str)
    str.tr('^0-9', '')
  end

  def stripDigits(str)
    str[-10..] || str
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: %i[show edit update destroy]

  # GET /students or /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.xlsx do
        response.headers[
          'Content-Disposition'
        ] = 'attachment; filename=students.xlsx'
      end
      format.html { render :index }
    end
  end

  # GET /students/1 or /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # # GET /students/deleteAll
  def deleteAll
    Student.delete_all
    # flash[:notice] = "You have removed all students!"
    redirect_to students_url
  end

  # GET /students/1/edit
  def edit; end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:First_Name, :Last_Name, :Phone_Number, :Email)
  end
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div class="field">
    <%= form.label :Student_ID 
    <%= form.text_field :Student_ID 
  </div> %>

  <br>

  <div class="field">
    <%= form.label :First_Name %>
    <%= form.text_field :First_Name %>
  </div>

  <br>

  <div class="field">
    <%= form.label :Last_Name %>
    <%= form.text_field :Last_Name %>
  </div>

  <br>

  <div class="field">
    <%= form.label :Phone_Number %>
    <%= form.text_field :Phone_Number %>
  </div>

  <br>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to '<button type="button">Edit</button>'.html_safe, @student %> |
<%= link_to '<button type="button">Back</button>'.html_safe, students_path %>

app/views/students/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Students</title>
</head>
<body id="body-pd">

  <h1>Students</h1>
  <p>Download this template and have students fill it out. Then, reupload the template.</p>
  <%= link_to '<button type="button">Download</button>'.html_safe, students_path(format: :xlsx)%> |
  <%= link_to '<button type="button">Upload</button>'.html_safe, new_students_import_path%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>StudentID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Phone number</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.id %></td>
          <td><%= student.First_Name %></td>
          <td><%= student.Last_Name %></td>
          <td><%= student.Phone_Number %></td>
          <td><%= student.Email %></td>
          <td><%= link_to '<i class="bx bx-search nav_icon"></i>'.html_safe, student %></td>
          <td><%= link_to '<i class="bx bx-pencil nav_icon"></i>'.html_safe, edit_student_path(student) %></td>
          <td><%= link_to '<i class="bx bx-trash nav_icon"></i>'.html_safe, student, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '<button type="button">Add Student</button>'.html_safe, new_student_path%> |
  <%= link_to '<button type="button">Delete All</button>'.html_safe, deleteAll_students_path, :method => :get,
    data: { confirm: 'Are you sure you want to delete all students?' } %>

</body>
</html>

<script>
	// highlight the current page
	var element = document.getElementById("2");
	element.classList.add("active");
</script>

app/views/students/index.xls.erb
<table border="1">
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Number</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  <% @students.each do |student| %>
      <tr>
        <td><%= student.first %></td>
        <td><%= student.last %></td>
        <td><%= student.number %></td>
        <td><%= student.email %></td>
      </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Students</title>
</head>
<body id="body-pd">

    <h1>Add New Student</h1>
    <%= render 'form', student: @student %>

    <br>
    
    <%= link_to '<button type="button">Back</button>'.html_safe, students_path %>


</body>
</html>

<script>
	// highlight the current page
	var element = document.getElementById("2");
	element.classList.add("active");
</script>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student id:</strong>
  <%= @student.Student_ID %>
</p>

<p>
  <strong>First name:</strong>
  <%= @student.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.Last_Name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @student.Phone_Number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.Email %>
</p>

<%= link_to '<button type="button">Edit</button>'.html_safe, edit_student_path(@student) %> |
<%= link_to '<button type="button">Back</button>'.html_safe, students_path %>