config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :masterkeys
  resources :message_histories
  resources :messages
  # resources :students

  resources :students do
    collection do
      get 'deleteAll'
    end
  end

  resources :students_imports, only: %i[new create]

  get 'students_imports/new'
  get 'students_imports/create'

  # devise_for :users
  devise_for :users, controllers: { registrations: 'user' }

  resources :message_histories
  resources :carriers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posttext', to: 'posttext#posttext'
  get 'home/dashboard'
  get 'home/homepage'
  root 'posttext#posttext'

  get  'help', to: 'help#index'
end

app/models/message_history.rb
# frozen_string_literal: true

class MessageHistory < ApplicationRecord
  validates :student_id, presence: true
  validates :message_id, presence: true
  validates :date_sent, presence: true
  has_many :message
  has_many :student, class_name: 'Student', foreign_key: 'Student_ID'
  has_many :admin
end

app/controllers/message_histories_controller.rb
# frozen_string_literal: true

# comment
class MessageHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message_history, only: %i[show edit update destroy]

  # GET /message_histories or /message_histories.json
  def index
    @message_histories = MessageHistory.all
  end

  # GET /message_histories/1 or /message_histories/1.json
  def show; end

  # GET /message_histories/new
  def new
    @message_history = MessageHistory.new
  end

  # GET /message_histories/1/edit
  def edit; end

  # POST /message_histories or /message_histories.json
  def create
    @message_history = MessageHistory.new(message_history_params)
    respond_to do |format|
      if @message_history.save
        format.html do
          redirect_to message_history_url(@message_history), notice: 'Message history was successfully created.'
        end
        format.json { render :show, status: :created, location: @message_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_histories/1 or /message_histories/1.json
  def update
    respond_to do |format|
      if @message_history.update(message_history_params)
        format.html do
          redirect_to message_history_url(@message_history), notice: 'Message history was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @message_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_histories/1 or /message_histories/1.json
  def destroy
    @message_history.destroy

    respond_to do |format|
      format.html { redirect_to message_histories_url, notice: 'Message history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message_history
    @message_history = MessageHistory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_history_params
    params.require(:message_history).permit(:message_id, :date_sent, :student_id)
  end
end

app/helpers/message_histories_helper.rb
# frozen_string_literal: true

module MessageHistoriesHelper
end

app/views/message_histories/_form.html.erb
<%= form_with(model: message_history) do |form| %>
  <% if message_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message_history.errors.count, "error") %> prohibited this message_history from being saved:</h2>

      <ul>
        <% message_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Message_ID %>
    <%= form.text_field :Message_ID %>
  </div>

  <div class="field">
    <%= form.label :Date_Sent %>
    <%= form.date_select :Date_Sent %>
  </div>

  <div class="field">
    <%= form.label :Student_ID %>
    <%= form.text_field :Student_ID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/message_histories/edit.html.erb
<h1>Editing Message History</h1>

<%= render 'form', message_history: @message_history %>

<%= link_to '<button type="button">Show</button>'.html_safe, @message_history %> |
<%= link_to '<button type="button">Back</button>'.html_safe, message_histories_path %>

<script>
	// highlight the current page
	var element = document.getElementById("3");
	element.classList.add("active");
</script>

app/views/message_histories/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Students</title>
</head>
<body id="body-pd">

  <h1>Message Histories</h1>

  <p id="notice"><%= notice %></p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Message ID</th>
        <th>Date sent</th>
        <th>Student ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @message_histories.each do |message_history| %>
        <tr>
          <td><%= message_history.message_id %></td>
          <td><%= message_history.date_sent %></td>
          <td><%= message_history.student_id %></td>
          <td><%= link_to '<i class="bx bx-search nav_icon"></i>'.html_safe, message_history %></td>
          <td><%= link_to '<i class="bx bx-pencil nav_icon"></i>'.html_safe, edit_message_history_path(message_history) %></td>
          <td><%= link_to '<i class="bx bx-trash nav_icon"></i>'.html_safe, message_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</body>
</html>

<script>
	// highlight the current page
	var element = document.getElementById("3");
	element.classList.add("active");
</script>

app/views/message_histories/new.html.erb
<h1>New Message History</h1>

<%= render 'form', message_history: @message_history %>

<%= link_to '<button type="button">Back</button>'.html_safe, message_histories_path %>

<script>
	// highlight the current page
	var element = document.getElementById("3");
	element.classList.add("active");
</script>

app/views/message_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @message_history.message_id %>
</p>

<p>
  <strong>Date sent:</strong>
  <%= @message_history.date_sent %>
</p>

<p>
  <strong>Student:</strong>
  <%= @message_history.student_id %>
</p>

<%= link_to '<button type="button">Edit</button>'.html_safe, edit_message_history_path(@message_history) %> |
<%= link_to '<button type="button">Back</button>'.html_safe, message_histories_path %>

<script>
	// highlight the current page
	var element = document.getElementById("3");
	element.classList.add("active");
</script>